# Generated by Django 2.2.11 on 2021-01-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_country_flag_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_file',
            field=models.ImageField(blank=True, help_text='Recomended size 512x512px', max_length=255, null=True, upload_to='images/geo/flags', verbose_name='Flag'),
        ),
    ]
