# Generated by Django 2.2.11 on 2021-01-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_auto_20210106_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='flag URL'),
        ),
    ]
