# Generated by Django 2.2.11 on 2021-01-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_auto_20210106_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
    ]
