# Generated by Django 3.0.5 on 2021-01-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0004_continent_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='flag URLs'),
        ),
    ]
