# Generated by Django 2.2.12 on 2020-06-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='points',
            field=models.IntegerField(default=1, verbose_name='Points on rating'),
        ),
    ]
