# Generated by Django 3.0.5 on 2020-04-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent',
            options={'verbose_name': 'continent'},
        ),
    ]
