# Generated by Django 3.0.5 on 2020-04-11 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200411_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
        migrations.AddField(
            model_name='country',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='published'),
        ),
        migrations.AddField(
            model_name='country',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='published at'),
        ),
    ]
