# Generated by Django 2.2.12 on 2020-07-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200702_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='cl_teams',
            field=models.IntegerField(default=1, verbose_name='The number of represented in the Champions League'),
        ),
        migrations.AddField(
            model_name='country',
            name='el_teams',
            field=models.IntegerField(default=1, verbose_name='The number of represented in the Europe League'),
        ),
    ]
