# Generated by Django 3.0.5 on 2020-04-11 19:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200411_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="Used to build the category's URL.", max_length=255, unique=True, verbose_name='slug')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published at')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league', to='main.Country', verbose_name='country')),
            ],
        ),
    ]
