# Generated by Django 3.0.5 on 2020-04-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_league'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country'},
        ),
    ]
