# Generated by Django 2.2.12 on 2020-07-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200702_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='points_ass',
            field=models.IntegerField(default=1, verbose_name='Points on association rating'),
        ),
    ]
