# Generated by Django 2.2.12 on 2020-07-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200702_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='points',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6, verbose_name='Points on rating'),
        ),
        migrations.AlterField(
            model_name='country',
            name='points_ass',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6, verbose_name='Points on association rating'),
        ),
    ]
