# Generated by Django 3.0.5 on 2020-04-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_club_reputation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='reputation',
        ),
        migrations.AddField(
            model_name='league',
            name='reputation',
            field=models.IntegerField(default=1),
        ),
    ]
