# Generated by Django 2.2.12 on 2020-07-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200702_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='points',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=7, verbose_name='Points on rating'),
        ),
    ]
