# Generated by Django 2.2.12 on 2020-07-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200703_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, help_text='Recomended size 512x512px', null=True, upload_to='images/flag', verbose_name='Image'),
        ),
    ]
