# Generated by Django 2.2.12 on 2020-07-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_country_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, help_text='Recomended size 512x512px', null=True, upload_to='images/flag', verbose_name='Flag'),
        ),
        migrations.AlterField(
            model_name='country',
            name='points_ass',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=7, verbose_name='Points on association rating'),
        ),
    ]
