# Generated by Django 2.2.14 on 2020-08-11 14:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200713_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='cl',
            field=models.IntegerField(blank=True, default=0, verbose_name='Champions League'),
        ),
        migrations.AlterField(
            model_name='club',
            name='founded',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Founded'),
        ),
        migrations.AlterField(
            model_name='club',
            name='gb',
            field=models.IntegerField(blank=True, default=0, verbose_name='Golden ball'),
        ),
        migrations.AlterField(
            model_name='club',
            name='main_text',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='club',
            name='main_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='club',
            name='main_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='club',
            name='main_text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='club',
            name='manager',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='club',
            name='manager_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='club',
            name='manager_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='club',
            name='manager_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='club',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='club',
            name='nickname_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='club',
            name='nickname_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='club',
            name='nickname_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='club',
            name='place',
            field=models.IntegerField(blank=True, default=1, verbose_name='Place on rating'),
        ),
        migrations.AlterField(
            model_name='club',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=7, verbose_name='Points on rating'),
        ),
        migrations.AlterField(
            model_name='club',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='club',
            name='short_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='club',
            name='short_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='club',
            name='short_name_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='club',
            name='stadium',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stadium'),
        ),
        migrations.AlterField(
            model_name='club',
            name='stadium_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stadium'),
        ),
        migrations.AlterField(
            model_name='club',
            name='stadium_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stadium'),
        ),
        migrations.AlterField(
            model_name='club',
            name='stadium_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stadium'),
        ),
        migrations.AlterField(
            model_name='club',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='associations',
            field=models.IntegerField(blank=True, default=1, verbose_name='Count of associations'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='founded',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Founded'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='located',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Located'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='located_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Located'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='located_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Located'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='located_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Located'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='main_text',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='main_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='main_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='main_text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='president',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='President'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='president_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='President'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='president_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='President'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='president_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='President'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='region_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='region_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='region_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='country',
            name='cl',
            field=models.IntegerField(blank=True, default=0, verbose_name='Champions League'),
        ),
        migrations.AlterField(
            model_name='country',
            name='cl_teams',
            field=models.IntegerField(blank=True, default=0, verbose_name='The number of represented in the Champions League'),
        ),
        migrations.AlterField(
            model_name='country',
            name='el_teams',
            field=models.IntegerField(blank=True, default=1, verbose_name='The number of represented in the Europe League'),
        ),
        migrations.AlterField(
            model_name='country',
            name='fifa',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Belonging to FIFA since'),
        ),
        migrations.AlterField(
            model_name='country',
            name='founded',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Founded'),
        ),
        migrations.AlterField(
            model_name='country',
            name='gb',
            field=models.IntegerField(blank=True, default=0, verbose_name='Golden ball'),
        ),
        migrations.AlterField(
            model_name='country',
            name='main_text',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='country',
            name='main_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='country',
            name='main_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='country',
            name='main_text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='country',
            name='place',
            field=models.IntegerField(blank=True, default=1, verbose_name='Place on rating'),
        ),
        migrations.AlterField(
            model_name='country',
            name='place_ass',
            field=models.IntegerField(blank=True, default=1, verbose_name='Place on association rating'),
        ),
        migrations.AlterField(
            model_name='country',
            name='points',
            field=models.IntegerField(blank=True, default=1, verbose_name='Points on rating'),
        ),
        migrations.AlterField(
            model_name='country',
            name='points_ass',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=7, verbose_name='Points on association rating'),
        ),
        migrations.AlterField(
            model_name='country',
            name='president',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='President'),
        ),
        migrations.AlterField(
            model_name='country',
            name='president_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='President'),
        ),
        migrations.AlterField(
            model_name='country',
            name='president_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='President'),
        ),
        migrations.AlterField(
            model_name='country',
            name='president_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='President'),
        ),
        migrations.AlterField(
            model_name='country',
            name='uefa',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Belonging to since'),
        ),
        migrations.AlterField(
            model_name='country',
            name='wc',
            field=models.IntegerField(blank=True, default=0, verbose_name='World Cup'),
        ),
        migrations.AlterField(
            model_name='country',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='founded',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Founded'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='main_text',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='main_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='main_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='main_text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cup', to='main.Continent', verbose_name='continent'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='league',
            name='count_team',
            field=models.IntegerField(blank=True, default=1, verbose_name='Number of teams:'),
        ),
        migrations.AlterField(
            model_name='league',
            name='founded',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Founded'),
        ),
        migrations.AlterField(
            model_name='league',
            name='last',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last winner'),
        ),
        migrations.AlterField(
            model_name='league',
            name='last_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last winner'),
        ),
        migrations.AlterField(
            model_name='league',
            name='last_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last winner'),
        ),
        migrations.AlterField(
            model_name='league',
            name='last_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last winner'),
        ),
        migrations.AlterField(
            model_name='league',
            name='main_text',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='league',
            name='main_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='league',
            name='main_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='league',
            name='main_text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='league',
            name='reputation',
            field=models.IntegerField(blank=True, default=1, verbose_name='Level on pyramid:'),
        ),
        migrations.AlterField(
            model_name='league',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='player',
            name='cl',
            field=models.IntegerField(blank=True, default=0, verbose_name='Champions League'),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gb',
            field=models.IntegerField(blank=True, default=0, verbose_name='Golden ball'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='player',
            name='main_text',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='player',
            name='main_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='player',
            name='main_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='player',
            name='main_text_uk',
            field=models.TextField(blank=True, null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname_uk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='player',
            name='positions',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='positions'),
        ),
        migrations.AlterField(
            model_name='player',
            name='positions_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='positions'),
        ),
        migrations.AlterField(
            model_name='player',
            name='positions_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='positions'),
        ),
        migrations.AlterField(
            model_name='player',
            name='positions_uk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='positions'),
        ),
        migrations.AlterField(
            model_name='player',
            name='wc',
            field=models.IntegerField(blank=True, default=0, verbose_name='World Cup'),
        ),
    ]
