# Generated by Django 2.2.14 on 2020-08-11 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200811_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='founded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Founded'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='founded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Founded'),
        ),
        migrations.AlterField(
            model_name='country',
            name='founded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Founded'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='founded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Founded'),
        ),
        migrations.AlterField(
            model_name='league',
            name='founded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Founded'),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of birth'),
        ),
    ]
