# Generated by Django 2.2.14 on 2020-08-13 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200811_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='main.Club', verbose_name='club')),
            ],
            options={
                'verbose_name': 'Player Club',
            },
        ),
        migrations.RemoveField(
            model_name='player',
            name='clubs',
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_from', models.PositiveIntegerField(blank=True, verbose_name='Year from')),
                ('year_to', models.PositiveIntegerField(blank=True, verbose_name='Year to')),
                ('games', models.PositiveIntegerField(blank=True, default=0, verbose_name='Games')),
                ('score', models.IntegerField(blank=True, default=0, verbose_name='Score')),
                ('is_load', models.BooleanField(default=False, verbose_name='Load')),
                ('playerclub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PlayerClub', verbose_name='PlayerClub')),
            ],
            options={
                'verbose_name': 'Year',
            },
        ),
        migrations.AddField(
            model_name='playerclub',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Player', verbose_name='Player'),
        ),
    ]
