# Generated by Django 2.2.14 on 2020-08-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200813_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Year',
        ),
    ]
