# Generated by Django 2.2.14 on 2020-08-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerclub',
            name='games',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Games'),
        ),
        migrations.AddField(
            model_name='playerclub',
            name='is_load',
            field=models.BooleanField(default=False, verbose_name='Load'),
        ),
        migrations.AddField(
            model_name='playerclub',
            name='score',
            field=models.IntegerField(blank=True, default=0, verbose_name='Score'),
        ),
        migrations.AddField(
            model_name='playerclub',
            name='year_from',
            field=models.PositiveIntegerField(blank=True, default=1900, verbose_name='Year from'),
        ),
        migrations.AddField(
            model_name='playerclub',
            name='year_to',
            field=models.PositiveIntegerField(blank=True, default=1900, verbose_name='Year to'),
        ),
    ]
