# Generated by Django 3.0.5 on 2020-04-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200412_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='picture',
            field=models.ImageField(blank=True, help_text='Recomended size 512x512px', null=True, upload_to='images/club', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='league',
            name='picture',
            field=models.ImageField(blank=True, help_text='Recomended size 512x512px', null=True, upload_to='images/league', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='country',
            name='picture',
            field=models.ImageField(blank=True, help_text='Recomended size 512x512px', null=True, upload_to='images/country', verbose_name='Image'),
        ),
    ]
