# Generated by Django 2.2.14 on 2020-08-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200814_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerclub',
            name='year_from',
            field=models.PositiveIntegerField(blank=True, verbose_name='Year from'),
        ),
        migrations.AlterField(
            model_name='playerclub',
            name='year_to',
            field=models.PositiveIntegerField(blank=True, verbose_name='Year to'),
        ),
    ]
