# Generated by Django 3.0.5 on 2020-04-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200412_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
