# Generated by Django 2.2.14 on 2020-08-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200814_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerclub',
            name='first_time',
            field=models.BooleanField(default=True, verbose_name='First time?'),
        ),
        migrations.AddField(
            model_name='playerclub',
            name='years_in_club',
            field=models.TextField(blank=True, null=True, verbose_name='Year in club'),
        ),
    ]
