# Generated by Django 3.0.5 on 2020-04-17 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200417_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='text',
            new_name='main_text',
        ),
        migrations.AddField(
            model_name='club',
            name='manager',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='founded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
