# Generated by Django 2.2.14 on 2020-08-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200814_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='famous_players',
        ),
    ]
