# Generated by Django 2.2.14 on 2020-08-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_club_famous_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.PositiveIntegerField(blank=True, verbose_name='Now much?')),
                ('years', models.TextField(blank=True, null=True, verbose_name='Years')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Player', verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Player Cup',
            },
        ),
    ]
