# Generated by Django 3.0.5 on 2020-04-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200417_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='website',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
