# Generated by Django 2.2.14 on 2020-08-19 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_playercup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cup',
            name='players',
        ),
        migrations.AddField(
            model_name='playercup',
            name='cup',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cup', to='main.Cup', verbose_name='Cup'),
        ),
    ]
