# Generated by Django 3.0.5 on 2020-04-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_pagehit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='PageHit',
        ),
        migrations.AddField(
            model_name='club',
            name='cups',
            field=models.ManyToManyField(to='main.Cup'),
        ),
    ]
