# Generated by Django 3.0.5 on 2020-04-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200417_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cup',
            options={'verbose_name': 'cup'},
        ),
        migrations.AlterField(
            model_name='club',
            name='cups',
            field=models.ManyToManyField(related_name='club', to='main.Cup', verbose_name='cup'),
        ),
    ]
