# Generated by Django 3.0.5 on 2020-04-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200417_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='cups',
        ),
        migrations.AddField(
            model_name='club',
            name='cups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club', to='main.Cup', verbose_name='cup'),
        ),
    ]
