# Generated by Django 2.2.14 on 2020-08-28 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_cupclub_cup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='cl',
        ),
        migrations.RemoveField(
            model_name='club',
            name='cups',
        ),
        migrations.RemoveField(
            model_name='club',
            name='gb',
        ),
        migrations.RemoveField(
            model_name='country',
            name='cl',
        ),
        migrations.RemoveField(
            model_name='country',
            name='gb',
        ),
        migrations.RemoveField(
            model_name='country',
            name='wc',
        ),
        migrations.RemoveField(
            model_name='cup',
            name='clubs',
        ),
        migrations.RemoveField(
            model_name='cup',
            name='countrys',
        ),
        migrations.RemoveField(
            model_name='player',
            name='cl',
        ),
        migrations.RemoveField(
            model_name='player',
            name='cups',
        ),
        migrations.RemoveField(
            model_name='player',
            name='gb',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wc',
        ),
        migrations.AlterField(
            model_name='playercup',
            name='cup',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Cup', verbose_name='Cup'),
        ),
        migrations.CreateModel(
            name='CupCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.PositiveIntegerField(blank=True, verbose_name='Now much?')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Country', verbose_name='Country')),
                ('cup', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Cup', verbose_name='Cup')),
            ],
            options={
                'verbose_name': 'Cup Country',
            },
        ),
    ]
