# Generated by Django 2.2.14 on 2020-08-28 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200828_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_from', models.PositiveIntegerField(blank=True, verbose_name='Year from')),
                ('year_to', models.PositiveIntegerField(blank=True, verbose_name='Year to')),
                ('first_time', models.BooleanField(default=True, verbose_name='First time?')),
                ('years', models.TextField(blank=True, null=True, verbose_name='Years')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Player', verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Cup Country',
            },
        ),
    ]
