# Generated by Django 3.0.5 on 2020-04-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200417_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='image',
            field=models.ImageField(blank=True, help_text='Recomended size 512x512px', null=True, upload_to='images/cup', verbose_name='Image'),
        ),
    ]
