# Generated by Django 3.0.5 on 2020-04-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_cup_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='cups',
        ),
        migrations.AddField(
            model_name='club',
            name='cups',
            field=models.ManyToManyField(related_name='club', to='main.Cup', verbose_name='cup'),
        ),
    ]
