# Generated by Django 2.2.14 on 2020-08-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_countryplayer_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryplayer',
            name='first_time',
        ),
        migrations.AddField(
            model_name='countryplayer',
            name='one_time',
            field=models.BooleanField(default=True, verbose_name='One time?'),
        ),
    ]
