# Generated by Django 3.0.5 on 2020-04-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200417_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Recomended size 512x512px', null=True, upload_to='images/plaayer', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'player',
            },
        ),
        migrations.AddField(
            model_name='club',
            name='famous_players',
            field=models.ManyToManyField(related_name='club', to='main.Player', verbose_name='player'),
        ),
    ]
