# Generated by Django 3.0.5 on 2020-04-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20200417_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='cups',
            field=models.ManyToManyField(blank=True, related_name='club', to='main.Cup', verbose_name='cup'),
        ),
        migrations.AlterField(
            model_name='club',
            name='famous_players',
            field=models.ManyToManyField(blank=True, related_name='club', to='main.Player', verbose_name='player'),
        ),
    ]
