# Generated by Django 3.0.5 on 2020-04-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200418_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
