# Generated by Django 3.0.5 on 2020-04-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_club_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='main_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='main_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='main_text_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='manager_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='manager_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='manager_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='title_uk',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
