# Generated by Django 2.2.14 on 2020-09-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200925_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='cl_teams',
        ),
        migrations.RemoveField(
            model_name='country',
            name='el_teams',
        ),
        migrations.RemoveField(
            model_name='country',
            name='place_ass',
        ),
        migrations.RemoveField(
            model_name='country',
            name='points_ass',
        ),
    ]
