# Generated by Django 3.0.5 on 2020-04-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200429_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='active',
        ),
    ]
