# Generated by Django 2.2.14 on 2020-09-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20200925_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingassociation',
            name='title',
            field=models.CharField(default='1', max_length=200, verbose_name='title'),
        ),
    ]
