# Generated by Django 2.2.14 on 2020-09-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_ratingassociation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingassociation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
