# Generated by Django 3.0.5 on 2020-04-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200429_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='title_uk',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
