# Generated by Django 2.2.14 on 2020-09-25 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200925_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RatingAssociation', verbose_name='Rating Associations'),
        ),
    ]
