# Generated by Django 3.0.5 on 2020-04-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20200429_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='slug_en',
            field=models.SlugField(help_text="Used to build the category's URL.", max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='continent',
            name='slug_ru',
            field=models.SlugField(help_text="Used to build the category's URL.", max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='continent',
            name='slug_uk',
            field=models.SlugField(help_text="Used to build the category's URL.", max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
    ]
