# Generated by Django 2.2.14 on 2020-10-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20200925_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='teams',
            field=models.CharField(blank=True, max_length=10, verbose_name='The number of represented Euro Cups'),
        ),
    ]
