# Generated by Django 2.2.14 on 2020-10-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20201005_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='no_teams',
            field=models.BooleanField(default=False, verbose_name='No team'),
        ),
    ]
