# Generated by Django 2.2.14 on 2020-10-05 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_association_no_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingassociation',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='published at'),
        ),
    ]
