# Generated by Django 3.0.5 on 2020-04-29 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20200429_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Club'},
        ),
        migrations.CreateModel(
            name='Kits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_file', models.FileField(blank=True, null=True, upload_to='post_files//%Y/%m/%d', verbose_name='File')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Club', verbose_name='Club')),
            ],
            options={
                'verbose_name': 'Post file',
            },
        ),
    ]
