# Generated by Django 2.2.14 on 2020-10-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_ratingassociation_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='country',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='country',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='country',
            name='title_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='title'),
        ),
    ]
