# Generated by Django 3.0.5 on 2020-04-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20200429_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kits',
            name='c_file',
            field=models.FileField(blank=True, null=True, upload_to='images/kits', verbose_name='Kit'),
        ),
    ]
