# Generated by Django 2.2.14 on 2020-10-08 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20201005_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Continent', verbose_name='continent')),
            ],
            options={
                'verbose_name': 'Rating Teams',
            },
        ),
        migrations.AddField(
            model_name='club',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club', to='main.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='association',
            name='rating',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.RatingAssociation', verbose_name='Rating Continent'),
        ),
        migrations.AlterField(
            model_name='club',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club', to='main.Continent', verbose_name='continent'),
        ),
        migrations.AlterField(
            model_name='club',
            name='league',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='club', to='main.League', verbose_name='league'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(blank=True, default=1, verbose_name='Place')),
                ('point_year1', models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=7, verbose_name='Points on association rating')),
                ('point_year2', models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=7, verbose_name='Points on association rating')),
                ('point_year3', models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=7, verbose_name='Points on association rating')),
                ('point_year4', models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=7, verbose_name='Points on association rating')),
                ('point_year5', models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=7, verbose_name='Points on association rating')),
                ('points', models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=7, verbose_name='Points on association rating')),
                ('club', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Club', verbose_name='Club')),
                ('rating', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.RatingTeam', verbose_name='Rating Continent')),
            ],
            options={
                'verbose_name': 'Team',
            },
        ),
    ]
