# Generated by Django 3.0.5 on 2020-04-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20200429_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kits',
            options={'verbose_name': 'Kit'},
        ),
        migrations.AlterField(
            model_name='kits',
            name='c_file',
            field=models.FileField(blank=True, null=True, upload_to='images/kits', verbose_name='Kits'),
        ),
    ]
