# Generated by Django 2.2.14 on 2020-10-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20201012_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='point_year1',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Points on association rating'),
        ),
        migrations.AlterField(
            model_name='team',
            name='point_year2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Points on association rating'),
        ),
        migrations.AlterField(
            model_name='team',
            name='point_year3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Points on association rating'),
        ),
        migrations.AlterField(
            model_name='team',
            name='point_year4',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Points on association rating'),
        ),
        migrations.AlterField(
            model_name='team',
            name='point_year5',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Points on association rating'),
        ),
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Points on association rating'),
        ),
    ]
