# Generated by Django 3.0.5 on 2020-04-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20200429_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kits',
            old_name='post',
            new_name='club',
        ),
        migrations.RenameField(
            model_name='kits',
            old_name='c_file',
            new_name='kits',
        ),
    ]
