# Generated by Django 3.0.5 on 2020-04-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20200429_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kits',
            name='kits',
            field=models.ImageField(blank=True, null=True, upload_to='images/kits', verbose_name='Kits'),
        ),
    ]
