# Generated by Django 3.0.5 on 2020-04-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20200429_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='kits',
            name='title',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
