# Generated by Django 2.2.14 on 2020-10-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20201012_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='place',
        ),
        migrations.RemoveField(
            model_name='club',
            name='points',
        ),
    ]
