# Generated by Django 3.0.5 on 2020-04-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_kits_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kits',
            name='title',
            field=models.CharField(default='Kits', max_length=200),
        ),
    ]
