# Generated by Django 2.2.14 on 2020-10-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_fifacountry_ratingcountry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingcountry',
            options={'verbose_name': 'Rating countryies'},
        ),
    ]
