# Generated by Django 3.0.5 on 2020-05-02 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20200429_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='slug',
            field=models.SlugField(help_text="Used to build the category's URL.", max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='player',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='player', to='main.Club', verbose_name='club'),
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='main.Country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='player',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='main_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='positions',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.SlugField(help_text="Used to build the category's URL.", max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.CreateModel(
            name='Fifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='FUT', max_length=200)),
                ('title_uk', models.CharField(default='FUT', max_length=200, null=True)),
                ('title_en', models.CharField(default='FUT', max_length=200, null=True)),
                ('title_ru', models.CharField(default='FUT', max_length=200, null=True)),
                ('kits', models.ImageField(blank=True, null=True, upload_to='images/fifa', verbose_name='Fifa')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Player', verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Fifa',
            },
        ),
    ]
