# Generated by Django 2.2.14 on 2020-10-15 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20201015_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fifacountry',
            name='country',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Country', verbose_name='Country'),
        ),
    ]
