# Generated by Django 3.0.5 on 2020-05-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20200502_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fifa',
            old_name='kits',
            new_name='cards',
        ),
    ]
