# Generated by Django 3.0.5 on 2020-05-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20200502_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fifa',
            name='title',
        ),
        migrations.RemoveField(
            model_name='fifa',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='fifa',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='fifa',
            name='title_uk',
        ),
    ]
