# Generated by Django 2.2.14 on 2020-10-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_player_photo_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'verbose_name': 'Association', 'verbose_name_plural': 'Associations'},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Club', 'verbose_name_plural': 'Clubs'},
        ),
        migrations.AlterModelOptions(
            name='continent',
            options={'verbose_name': 'continent', 'verbose_name_plural': 'Continents'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='countryplayer',
            options={'verbose_name': 'Cup Country', 'verbose_name_plural': 'Cup Country'},
        ),
        migrations.AlterModelOptions(
            name='cup',
            options={'verbose_name': 'cup', 'verbose_name_plural': 'Cups'},
        ),
        migrations.AlterModelOptions(
            name='cupclub',
            options={'verbose_name': 'Cup Club', 'verbose_name_plural': 'Cup Club'},
        ),
        migrations.AlterModelOptions(
            name='cupcountry',
            options={'verbose_name': 'Cup Country', 'verbose_name_plural': 'Cup Country'},
        ),
        migrations.AlterModelOptions(
            name='fifa',
            options={'verbose_name': 'Fifa', 'verbose_name_plural': 'Fifa'},
        ),
        migrations.AlterModelOptions(
            name='fifacountry',
            options={'verbose_name': 'FifaCountry', 'verbose_name_plural': 'FifaCountry'},
        ),
        migrations.AlterModelOptions(
            name='kits',
            options={'verbose_name': 'Kit', 'verbose_name_plural': 'Kits'},
        ),
        migrations.AlterModelOptions(
            name='league',
            options={'verbose_name': 'league', 'verbose_name_plural': 'Leagues'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AlterModelOptions(
            name='playerclub',
            options={'verbose_name': 'Player Club', 'verbose_name_plural': 'Player Club'},
        ),
        migrations.AlterModelOptions(
            name='playercup',
            options={'verbose_name': 'Player Cup', 'verbose_name_plural': 'Player Cup'},
        ),
        migrations.AlterModelOptions(
            name='ratingassociation',
            options={'verbose_name': 'Rating Associations', 'verbose_name_plural': 'Rating Associations'},
        ),
        migrations.AlterModelOptions(
            name='ratingcountry',
            options={'verbose_name': 'Rating countryies', 'verbose_name_plural': 'Rating countryies'},
        ),
        migrations.AlterModelOptions(
            name='ratingteam',
            options={'verbose_name': 'Rating Teams', 'verbose_name_plural': 'Rating Teams'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
    ]
