# Generated by Django 3.0.5 on 2020-05-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20200502_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='positions_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='positions_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='positions_uk',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
