# Generated by Django 3.0.5 on 2020-05-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20200502_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='main_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='main_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='main_text_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nickname_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nickname_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nickname_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
