# Generated by Django 3.0.5 on 2020-05-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_cup_main_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='cup', to='main.Club', verbose_name='club'),
        ),
        migrations.AddField(
            model_name='cup',
            name='countrys',
            field=models.ManyToManyField(blank=True, related_name='cup', to='main.Country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='cup',
            name='main_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cup',
            name='main_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cup',
            name='main_text_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cup',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='cup', to='main.Player', verbose_name='player'),
        ),
    ]
