# Generated by Django 3.0.5 on 2020-05-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20200502_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gb',
            field=models.IntegerField(default=0),
        ),
    ]
