# Generated by Django 3.0.5 on 2020-05-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_player_gb'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='cl',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='club',
            name='gb',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='country',
            name='cl',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='country',
            name='gb',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='country',
            name='wc',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='cl',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='wc',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='gb',
            field=models.IntegerField(default=1),
        ),
    ]
