# Generated by Django 3.0.5 on 2020-05-02 18:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_auto_20200502_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='founded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cup',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cup', to='main.Continent', verbose_name='continent'),
        ),
        migrations.AddField(
            model_name='cup',
            name='website',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='cl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='gb',
            field=models.IntegerField(default=0),
        ),
    ]
