# Generated by Django 3.0.5 on 2020-05-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20200502_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='league',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
    ]
