# Generated by Django 3.0.5 on 2020-05-10 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20200509_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='founded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Founded'),
        ),
        migrations.AddField(
            model_name='continent',
            name='image',
            field=models.ImageField(blank=True, help_text='Recomended size 512x512px', null=True, upload_to='images/cup', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='continent',
            name='located',
            field=models.CharField(max_length=255, null=True, verbose_name='Nickname'),
        ),
        migrations.AddField(
            model_name='continent',
            name='main_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='membership',
            field=models.CharField(max_length=255, null=True, verbose_name='Nickname'),
        ),
        migrations.AddField(
            model_name='continent',
            name='region',
            field=models.CharField(max_length=255, null=True, verbose_name='Nickname'),
        ),
        migrations.AddField(
            model_name='continent',
            name='website',
            field=models.URLField(max_length=255, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='club',
            name='cl',
            field=models.IntegerField(default=0, verbose_name='Champions League'),
        ),
        migrations.AlterField(
            model_name='club',
            name='cups',
            field=models.ManyToManyField(blank=True, help_text='Use CTRL for select more than one', related_name='club', to='main.Cup', verbose_name='cup'),
        ),
        migrations.AlterField(
            model_name='club',
            name='famous_players',
            field=models.ManyToManyField(blank=True, help_text='Use CTRL for select more than one', related_name='club', to='main.Player', verbose_name='player'),
        ),
        migrations.AlterField(
            model_name='club',
            name='founded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Founded'),
        ),
        migrations.AlterField(
            model_name='club',
            name='gb',
            field=models.IntegerField(default=0, verbose_name='Golden ball'),
        ),
        migrations.AlterField(
            model_name='club',
            name='main_text',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='club',
            name='main_text_en',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='club',
            name='main_text_ru',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='club',
            name='main_text_uk',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='club',
            name='manager',
            field=models.CharField(max_length=255, null=True, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='club',
            name='manager_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='club',
            name='manager_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='club',
            name='manager_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='club',
            name='nickname',
            field=models.CharField(max_length=255, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='club',
            name='nickname_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='club',
            name='nickname_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='club',
            name='nickname_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='club',
            name='picture',
            field=models.ImageField(blank=True, help_text='Recomended size 512x512px', null=True, upload_to='images/club', verbose_name='Club emblem'),
        ),
        migrations.AlterField(
            model_name='club',
            name='short_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='club',
            name='short_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='club',
            name='short_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='club',
            name='short_name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='club',
            name='stadium',
            field=models.CharField(max_length=255, null=True, verbose_name='Stadium'),
        ),
        migrations.AlterField(
            model_name='club',
            name='stadium_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Stadium'),
        ),
        migrations.AlterField(
            model_name='club',
            name='stadium_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Stadium'),
        ),
        migrations.AlterField(
            model_name='club',
            name='stadium_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Stadium'),
        ),
        migrations.AlterField(
            model_name='club',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='club',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='club',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='club',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='club',
            name='website',
            field=models.URLField(max_length=255, null=True, verbose_name='Website'),
        ),
    ]
