# Generated by Django 3.0.5 on 2020-05-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20200510_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continent',
            name='membership',
        ),
        migrations.AddField(
            model_name='continent',
            name='associations',
            field=models.IntegerField(default=1, verbose_name='Count of associations'),
        ),
        migrations.AddField(
            model_name='continent',
            name='president',
            field=models.CharField(max_length=255, null=True, verbose_name='President'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='image',
            field=models.ImageField(blank=True, help_text='Recomended size 512x512px', null=True, upload_to='images/continent', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='located',
            field=models.CharField(max_length=255, null=True, verbose_name='Located'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='main_text',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='region',
            field=models.CharField(max_length=255, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
    ]
