# Generated by Django 3.0.5 on 2020-05-10 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_auto_20200510_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='published at'),
        ),
    ]
