# Generated by Django 3.0.5 on 2020-05-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_continent_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='located_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Located'),
        ),
        migrations.AddField(
            model_name='continent',
            name='located_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Located'),
        ),
        migrations.AddField(
            model_name='continent',
            name='located_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Located'),
        ),
        migrations.AddField(
            model_name='continent',
            name='main_text_en',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AddField(
            model_name='continent',
            name='main_text_ru',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AddField(
            model_name='continent',
            name='main_text_uk',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AddField(
            model_name='continent',
            name='president_en',
            field=models.CharField(max_length=255, null=True, verbose_name='President'),
        ),
        migrations.AddField(
            model_name='continent',
            name='president_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='President'),
        ),
        migrations.AddField(
            model_name='continent',
            name='president_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='President'),
        ),
        migrations.AddField(
            model_name='continent',
            name='region_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='continent',
            name='region_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='continent',
            name='region_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Region'),
        ),
    ]
