# Generated by Django 2.2.2 on 2020-05-22 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20200510_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='fifa',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='FIFA affiliation'),
        ),
        migrations.AddField(
            model_name='country',
            name='founded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Founded'),
        ),
        migrations.AddField(
            model_name='country',
            name='main_text',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AddField(
            model_name='country',
            name='president',
            field=models.CharField(max_length=255, null=True, verbose_name='President'),
        ),
        migrations.AddField(
            model_name='country',
            name='uefa',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='FIFA affiliation'),
        ),
        migrations.AddField(
            model_name='country',
            name='website',
            field=models.URLField(max_length=255, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='country',
            name='cl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='gb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='country',
            name='wc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='cl',
            field=models.IntegerField(default=0, verbose_name='Champions League'),
        ),
        migrations.AlterField(
            model_name='player',
            name='clubs',
            field=models.ManyToManyField(blank=True, help_text='Use CTRL for select more than one', related_name='player', to='main.Club', verbose_name='club'),
        ),
        migrations.AlterField(
            model_name='player',
            name='cups',
            field=models.ManyToManyField(blank=True, help_text='Use CTRL for select more than one', related_name='player', to='main.Cup', verbose_name='cup'),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gb',
            field=models.IntegerField(default=0, verbose_name='Golden ball'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.FloatField(null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='player',
            name='main_text',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='player',
            name='main_text_en',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='player',
            name='main_text_ru',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='player',
            name='main_text_uk',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(max_length=255, null=True, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname_en',
            field=models.CharField(max_length=255, null=True, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='player',
            name='positions',
            field=models.CharField(max_length=50, null=True, verbose_name='positions'),
        ),
        migrations.AlterField(
            model_name='player',
            name='positions_en',
            field=models.CharField(max_length=50, null=True, verbose_name='positions'),
        ),
        migrations.AlterField(
            model_name='player',
            name='positions_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='positions'),
        ),
        migrations.AlterField(
            model_name='player',
            name='positions_uk',
            field=models.CharField(max_length=50, null=True, verbose_name='positions'),
        ),
        migrations.AlterField(
            model_name='player',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='player',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='player',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='player',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='player',
            name='wc',
            field=models.IntegerField(default=0, verbose_name='World Cup'),
        ),
    ]
