# Generated by Django 2.2.2 on 2020-05-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_auto_20200522_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='main_text_en',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AddField(
            model_name='country',
            name='main_text_ru',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AddField(
            model_name='country',
            name='main_text_uk',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AddField(
            model_name='country',
            name='president_en',
            field=models.CharField(max_length=255, null=True, verbose_name='President'),
        ),
        migrations.AddField(
            model_name='country',
            name='president_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='President'),
        ),
        migrations.AddField(
            model_name='country',
            name='president_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='President'),
        ),
    ]
