# Generated by Django 2.2.2 on 2020-05-22 16:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20200522_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='count_team',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='league',
            name='founded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Founded'),
        ),
        migrations.AddField(
            model_name='league',
            name='last',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='last', to='main.Club', verbose_name='club'),
        ),
        migrations.AddField(
            model_name='league',
            name='main_text',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AddField(
            model_name='league',
            name='website',
            field=models.URLField(max_length=255, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='country',
            name='uefa',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='UEFA affiliation'),
        ),
    ]
