# Generated by Django 2.2.2 on 2020-05-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20200522_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='last',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last', to='main.Club', verbose_name='club'),
        ),
    ]
