# Generated by Django 2.2.2 on 2020-05-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_remove_league_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='count_team',
        ),
        migrations.RemoveField(
            model_name='league',
            name='founded',
        ),
        migrations.RemoveField(
            model_name='league',
            name='main_text',
        ),
        migrations.RemoveField(
            model_name='league',
            name='website',
        ),
    ]
