# Generated by Django 2.2.2 on 2020-05-22 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_auto_20200522_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='fifa',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='FIFA affiliation'),
        ),
        migrations.AddField(
            model_name='country',
            name='founded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Founded'),
        ),
        migrations.AddField(
            model_name='country',
            name='main_text',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AddField(
            model_name='country',
            name='main_text_en',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AddField(
            model_name='country',
            name='main_text_ru',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AddField(
            model_name='country',
            name='main_text_uk',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AddField(
            model_name='country',
            name='president',
            field=models.CharField(max_length=255, null=True, verbose_name='President'),
        ),
        migrations.AddField(
            model_name='country',
            name='president_en',
            field=models.CharField(max_length=255, null=True, verbose_name='President'),
        ),
        migrations.AddField(
            model_name='country',
            name='president_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='President'),
        ),
        migrations.AddField(
            model_name='country',
            name='president_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='President'),
        ),
        migrations.AddField(
            model_name='country',
            name='uefa',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='UEFA affiliation'),
        ),
        migrations.AddField(
            model_name='country',
            name='website',
            field=models.URLField(max_length=255, null=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='league',
            name='count_team',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='league',
            name='founded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Founded'),
        ),
        migrations.AddField(
            model_name='league',
            name='last',
            field=models.CharField(max_length=255, null=True, verbose_name='Last winner'),
        ),
        migrations.AddField(
            model_name='league',
            name='main_text',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AddField(
            model_name='league',
            name='website',
            field=models.URLField(max_length=255, null=True, verbose_name='Website'),
        ),
    ]
