# Generated by Django 2.2.2 on 2020-05-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_league_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='main_text',
            field=models.TextField(null=True),
        ),
    ]
