# Generated by Django 2.2.2 on 2020-05-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_auto_20200522_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='last',
            field=models.CharField(max_length=255, null=True, verbose_name='Last winner'),
        ),
    ]
