# Generated by Django 2.2.2 on 2020-05-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_auto_20200522_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='last_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Last winner'),
        ),
        migrations.AddField(
            model_name='league',
            name='last_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Last winner'),
        ),
        migrations.AddField(
            model_name='league',
            name='last_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Last winner'),
        ),
        migrations.AddField(
            model_name='league',
            name='main_text_en',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AddField(
            model_name='league',
            name='main_text_ru',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AddField(
            model_name='league',
            name='main_text_uk',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
    ]
