# Generated by Django 2.2.2 on 2020-05-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_auto_20200522_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='last',
        ),
        migrations.RemoveField(
            model_name='league',
            name='last_en',
        ),
        migrations.RemoveField(
            model_name='league',
            name='last_ru',
        ),
        migrations.RemoveField(
            model_name='league',
            name='last_uk',
        ),
    ]
