# Generated by Django 3.0.5 on 2020-05-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_auto_20200522_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='main_text',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AddField(
            model_name='league',
            name='main_text_en',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AddField(
            model_name='league',
            name='main_text_ru',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AddField(
            model_name='league',
            name='main_text_uk',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
    ]
