# Generated by Django 3.0.5 on 2020-05-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_auto_20200522_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='count_team',
        ),
        migrations.RemoveField(
            model_name='league',
            name='founded',
        ),
    ]
