# Generated by Django 3.0.5 on 2020-05-22 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_auto_20200522_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='count_team',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='league',
            name='founded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Founded'),
        ),
    ]
