# Generated by Django 3.0.5 on 2020-05-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_auto_20200522_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='website',
        ),
    ]
