# Generated by Django 3.0.5 on 2020-05-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_remove_league_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='website',
            field=models.URLField(max_length=255, null=True, verbose_name='Website'),
        ),
    ]
