# Generated by Django 2.2.2 on 2020-05-22 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_league_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='fifa',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Belonging to FIFA since'),
        ),
        migrations.AlterField(
            model_name='country',
            name='uefa',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Belonging to since'),
        ),
    ]
