# Generated by Django 2.2.12 on 2020-06-14 21:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_auto_20200522_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='continent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club', to='main.Continent', verbose_name='continent'),
        ),
        migrations.AlterField(
            model_name='country',
            name='cl',
            field=models.IntegerField(default=0, verbose_name='Champions League'),
        ),
        migrations.AlterField(
            model_name='country',
            name='gb',
            field=models.IntegerField(default=0, verbose_name='Golden ball'),
        ),
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='country',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='country',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='country',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='country',
            name='wc',
            field=models.IntegerField(default=0, verbose_name='World Cup'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='clubs',
            field=models.ManyToManyField(blank=True, help_text='Use CTRL for select more than one', related_name='cup', to='main.Club', verbose_name='club'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='countrys',
            field=models.ManyToManyField(blank=True, help_text='Use CTRL for select more than one', related_name='cup', to='main.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='founded',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Founded'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='main_text',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='main_text_en',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='main_text_ru',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='main_text_uk',
            field=models.TextField(null=True, verbose_name='main text'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='players',
            field=models.ManyToManyField(blank=True, help_text='Use CTRL for select more than one', related_name='cup', to='main.Player', verbose_name='player'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='cup',
            name='website',
            field=models.URLField(max_length=255, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='league',
            name='count_team',
            field=models.IntegerField(default=1, verbose_name='Number of teams:'),
        ),
        migrations.AlterField(
            model_name='league',
            name='reputation',
            field=models.IntegerField(default=1, verbose_name='Level on pyramid:'),
        ),
        migrations.AlterField(
            model_name='league',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='league',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='league',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='league',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
    ]
