# Generated by Django 2.2.12 on 2020-06-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_auto_20200615_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='place',
            field=models.IntegerField(default=1, verbose_name='Place on rating'),
        ),
        migrations.AddField(
            model_name='club',
            name='points',
            field=models.IntegerField(default=1, verbose_name='Points on rating'),
        ),
    ]
