# Generated by Django 2.2.12 on 2020-06-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_auto_20200616_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='points',
            field=models.FloatField(default=1, verbose_name='Points on rating'),
        ),
    ]
