# Generated by Django 2.2.12 on 2020-06-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_auto_20200616_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='place',
        ),
    ]
