# Generated by Django 2.2.12 on 2020-06-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_remove_club_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='place',
            field=models.IntegerField(default=1, verbose_name='Place on rating'),
        ),
    ]
