# Generated by Django 3.0.5 on 2020-06-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_club_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='place',
            field=models.IntegerField(default=1, verbose_name='Place on rating'),
        ),
        migrations.AddField(
            model_name='country',
            name='points',
            field=models.FloatField(default=1.0, verbose_name='Points on rating'),
        ),
    ]
