# Generated by Django 2.2.12 on 2020-06-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_auto_20200616_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='place',
            field=models.IntegerField(verbose_name='Place on rating'),
        ),
        migrations.AlterField(
            model_name='club',
            name='points',
            field=models.FloatField(verbose_name='Points on rating'),
        ),
    ]
