# Generated by Django 2.2.12 on 2020-06-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_auto_20200616_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='place',
            field=models.IntegerField(default=1, verbose_name='Place on rating'),
        ),
        migrations.AlterField(
            model_name='club',
            name='points',
            field=models.FloatField(default=1.0, verbose_name='Points on rating'),
        ),
    ]
